### ISSUE TITLE
patator phpmyadmin brute force

### ISSUE THREAD

**Issue by italy2010** [lanjelot/patator#1]
Hello , i tested patator on  localhost and it was ok, (wamp server phpmyadmin).

but now i test it on online webserver and it respond http ok for every password!.

where is my problem?
## 

22:00:58 patator    INFO - 200  686:0          0.139 | 111111                             |    21 | HTTP/1.1 200 OK
22:00:58 patator    INFO - 200  686:0          0.129 | iloveu                             |    22 | HTTP/1.1 200 OK
22:00:58 patator    INFO - 200  686:0          0.124 | 000000                             |    23 | HTTP/1.1 200 OK
22:00:58 patator    INFO - 200  686:0          0.119 | monkey                             |    14 | HTTP/1.1 200 OK
22:00:58 patator    INFO - 200  688:0          0.153 | lovely                             |    15 | HTTP/1.1 200 OK
22:00:58 patator    INFO - 200  688:0          0.147 | sunshine                           |    26 | HTTP/1.1 200 OK
22:00:58 patator    INFO - 200  688:0          0.148 | michael                            |    18 | HTTP/1.1 200 OK
22:00:58 patator    INFO - 200  686:0          0.133 | qwerty                             |    20 | HTTP/1.1 200 OK

---

post method is like this:
pma_username=root&pma_password=root&server=1&target=index.php&token=47280f4e9dac7db66d3864bd6f61f4c0

**Comment by nikolaykv** [comment]
Strange, I get exactly the same problem. Myadmin version cannot be determined
