### ISSUE TITLE
Resolving timed out after 10000 milliseconds

### ISSUE THREAD

**Issue by sunbyte** [lanjelot/patator#104]
Hi, why <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds') is returned all the time in working network? Thanks.

code size:clen       time | candidate                          |   num | mesg
-----------------------------------------------------------------------------
xxx  75:-1         51.150 | 123456                             |     1 | <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds')
xxx  75:-1         51.151 | 123456789                          |     5 | <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds')
xxx  75:-1         51.141 | 12345678                           |     6 | <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds')
xxx  75:-1         51.130 | abc123                             |     8 | <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds')
xxx  75:-1         51.127 | computer                           |     9 | <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds')
xxx  75:-1         51.177 | 12345                              |     2 | <class 'pycurl.error'> (28, 'Resolving timed out after 10015 milliseconds')
xxx  75:-1         51.147 | password                           |     3 | <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds')
xxx  75:-1         51.212 | password1                          |     4 | <class 'pycurl.error'> (28, 'Resolving timed out after 10015 milliseconds')
xxx  75:-1         51.148 | 1234567890                         |     7 | <class 'pycurl.error'> (28, 'Resolving timed out after 10000 milliseconds')
xxx  75:-1         51.166 | tigger                             |    10 | <class 'pycurl.error'> (28, 'Resolving timed out after 10015 milliseconds')

**Comment by rodneymullen3** [comment]
I have the same problem but this is pycurl problem. Pycurl is just sucks. ping, wget, curl everything works except pycurl....

PS D:\> curl http://XXXXXXXXa/FILE0/
curl : The remote server returned an error: (404) Not Found. <-- (good response)

PS D:\> ping rtt.kl.com.ua
Pinging XXXXX [5.79.66.145] with 32 bytes of data:
Reply from 5.79.66.145: bytes=32 time=28ms TTL=56 <-- (good response)


14:46:32 patator    FAIL - xxx  75:-1         51.086 | XXXXX                            |     7 | <class 'pycurl.error'> (28, 'Resolving timed out after 10001 milliseconds')   <-- (.......pycurlfail)

**Comment by lanjelot** [comment]
can you give target hostname that's causing the issue please
