### ISSUE TITLE
Timeout error and ignoring it

### ISSUE THREAD

**Issue by nemonnet** [lanjelot/patator#109]
Launch string
`./patator.py http_fuzz url="FILE2/test.cgi" -l ./data/ method=GET user_pass=FILE0:FILE1 0=login.txt 1=pwd.txt 2=target.txt timeout=3 --threads 1`

Work log
13:10:11 patator    INFO - -----------------------------------------------------------------------------
13:10:28 patator    FAIL - xxx  75:-1         16.027 | admin:1:192.168.12.15:81           |     1 | <class 'pycurl.error'> (28, 'Connection timed out after 3004 milliseconds')
13:10:44 patator    FAIL - xxx  75:-1         16.032 | admin:12:192.168.12.15:81          |     2 | <class 'pycurl.error'> (28, 'Connection timed out after 3002 milliseconds')
13:11:01 patator    FAIL - xxx  75:-1         16.017 | admin:123:192.168.12.15:81         |     3 | <class 'pycurl.error'> (28, 'Connection timed out after 3001 milliseconds')

Target - non-existent IP address for check.
How to ignore target ip after the first timeout?
And judging by the log, the time between requests is 17 seconds, not 3. Perhaps this is due to a timeout error.

If specify the number of threads 3, then all three attempts will show an error after 17 seconds simultaneously.
13:17:20 patator    INFO - -----------------------------------------------------------------------------
13:17:37 patator    FAIL - xxx  75:-1         16.017 | admin:1:192.168.12.15:81           |     1 | <class 'pycurl.error'> (28, 'Connection timed out after 3001 milliseconds')
13:17:37 patator    FAIL - xxx  75:-1         16.019 | admin:12:192.168.12.15:81          |     2 | <class 'pycurl.error'> (28, 'Connection timed out after 3001 milliseconds')
13:17:37 patator    FAIL - xxx  75:-1         16.017 | admin:123:192.168.12.15:81         |     3 | <class 'pycurl.error'> (28, 'Connection timed out after 3001 milliseconds')

**Comment by lanjelot** [comment]
Use `-x free=host:fgrep='timed out' --allow-ignore-failures`

And it shows 17 seconds because the time out is 3 seconds and --max-retries is 5 by default (3*5 => 15 seconds)
