### ISSUE TITLE
pip error: Command "python setup.py egg_info" failed with error code 1

### ISSUE THREAD

**Issue by tokyoneon** [lanjelot/patator#111]
Installed setuptools:

	$ apt-get install python-setuptools

	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	python-setuptools is already the newest version (40.8.0-1).
	python-setuptools set to manually installed.
	0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

Tried upgrading via `pip`.

	$ pip install --upgrade setuptools

	Requirement already up-to-date: setuptools in /usr/lib/python2.7/dist-packages (40.8.0)

Some version info:

	$ pip --version

	pip 19.0.3 from /usr/local/lib/python2.7/dist-packages/pip (python 2.7)

	$ python --version

	Python 2.7.16rc1

	$ lsb_release -a

	Distributor ID:	Kali
	Description:	Kali GNU/Linux Rolling
	Release:	2019.1
	Codename:	n/a

Error:

	$ pip install -r requirements.txt 

	DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
	Collecting paramiko (from -r requirements.txt (line 1))
	  Using cached https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl
	Collecting pycurl (from -r requirements.txt (line 2))
	  Using cached https://files.pythonhosted.org/packages/e8/e4/0dbb8735407189f00b33d84122b9be52c790c7c3b25286826f4e1bdb7bde/pycurl-7.43.0.2.tar.gz
		Complete output from command python setup.py egg_info:
		Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "/tmp/pip-install-HDCwhD/pycurl/setup.py", line 913, in <module>
			ext = get_extension(sys.argv, split_extension_source=split_extension_source)
		  File "/tmp/pip-install-HDCwhD/pycurl/setup.py", line 582, in get_extension
			ext_config = ExtensionConfiguration(argv)
		  File "/tmp/pip-install-HDCwhD/pycurl/setup.py", line 99, in __init__
			self.configure()
		  File "/tmp/pip-install-HDCwhD/pycurl/setup.py", line 227, in configure_unix
			raise ConfigurationError(msg)
		__main__.ConfigurationError: Could not run curl-config: [Errno 2] No such file or directory
		
		----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-HDCwhD/pycurl/

I got around the error by installing `python-pycurl` with APT, but same egg_info error with other depends:

	$ pip install -r requirements.txt 

	Collecting paramiko (from -r requirements.txt (line 1))
	  Using cached https://files.pythonhosted.org/packages/cf/ae/94e70d49044ccc234bfdba20114fa947d7ba6eb68a2e452d89b920e62227/paramiko-2.4.2-py2.py3-none-any.whl
	Requirement already satisfied: pycurl in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 2)) (7.43.0.2)
	Collecting ajpy (from -r requirements.txt (line 3))
	  Downloading https://files.pythonhosted.org/packages/12/dd/e641d8c0b3b14eed50122a3c090ff9150bd0988fd0790d4819cd8083e83d/ajpy-0.0.4.tar.gz
	Requirement already satisfied: pyopenssl in /usr/lib/python2.7/dist-packages (from -r requirements.txt (line 5)) (19.0.0)
	Collecting cx_Oracle (from -r requirements.txt (line 6))
	  Downloading https://files.pythonhosted.org/packages/6e/88/d8bf4d511231f2e96866d068ebf71278c611296acb803520658d3735e980/cx_Oracle-7.1.1-cp27-cp27mu-manylinux1_x86_64.whl (674kB)
		100% |████████████████████████████████| 675kB 181kB/s 
	Collecting mysqlclient (from -r requirements.txt (line 7))
	  Downloading https://files.pythonhosted.org/packages/f4/f1/3bb6f64ca7a429729413e6556b7ba5976df06019a5245a43d36032f1061e/mysqlclient-1.4.2.post1.tar.gz (85kB)
		100% |████████████████████████████████| 92kB 249kB/s 
		Complete output from command python setup.py egg_info:
		sh: 1: mysql_config: not found
		Traceback (most recent call last):
		  File "<string>", line 1, in <module>
		  File "/tmp/pip-install-nfKGZ6/mysqlclient/setup.py", line 16, in <module>
			metadata, options = get_config()
		  File "setup_posix.py", line 51, in get_config
			libs = mysql_config("libs")
		  File "setup_posix.py", line 29, in mysql_config
			raise EnvironmentError("%s not found" % (_mysql_config_path,))
		EnvironmentError: mysql_config not found
		
		----------------------------------------
	Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-nfKGZ6/mysqlclient/

**Comment by lanjelot** [comment]
have a look at the Vagrantfile https://github.com/lanjelot/patator/blob/master/Vagrantfile#L14

**Comment by qinggegeya** [comment]
> have a look at the Vagrantfile https://github.com/lanjelot/patator/blob/master/Vagrantfile#L14

I've tried what you said，But it still doesn't work


`  ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-vCjLsx/mysqlclient/setup.py'"'"'; __file__='"'"'/tmp/pip-install-vCjLsx/mysqlclient/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-3UHjow
         cwd: /tmp/pip-install-vCjLsx/mysqlclient/
    Complete output (12 lines):
    sh: 1: mysql_config: not found
    sh: 1: mariadb_config: not found
    sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-vCjLsx/mysqlclient/setup.py", line 16, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 61, in get_config
        libs = mysql_config("libs")
      File "setup_posix.py", line 29, in mysql_config
        raise EnvironmentError("%s not found" % (_mysql_config_path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
`
