### ISSUE TITLE
VNC brute forcing not working

### ISSUE THREAD

**Issue by vincentcox** [lanjelot/patator#112]
I cannot get patator to work with VNC brute forcing. Here is what I tried:
```
┌─[✗]─[root@oscp]─[~/tools/]
└──╼ #patator vnc_login host=10.11.1.X password=FILE0 0=/usr/share/wordlists/rockyou.txt –t 1 –x retry:fgep!='Authentication failure' --max-retries 0 –x quit:code=0
Traceback (most recent call last):
  File "/usr/bin/patator", line 4913, in <module>
    powder = ctrl(module, [name] + sys.argv[1:])
  File "/usr/bin/patator", line 1458, in __init__
    for k, v in self.expand_key(arg):
ValueError: not enough values to unpack (expected 2, got 1)
```

No idea why it is throwing that error... Any ideas?
I did some research about patator and VNC brute forcing, but not much to find about that.

**Comment by lanjelot** [comment]
You need to quote `!` because it's expanded by your shell ;)

**Comment by vincentcox** [comment]
Still not working:
`patator vnc_login host=10.11.1.X password=FILE0 0=/usr/share/wordlists/rockyou.txt –t 1 -x 'retry:fgrep!=Authentication failure' --max-retries 0`

![image](https://user-images.githubusercontent.com/9286611/57690145-48551c80-7641-11e9-87ac-3354fbd5ce44.png)

**Comment by vincentcox** [comment]
Seemed to be a "-" malformed. Works now!
`patator vnc_login host=10.11.1.1 password=FILE0 0='~/tools/SecLists/Passwords/darkweb2017-top10.txt' -t 1 -x "retry:fgrep!=Authentication failure" --max-retries 0`
