### ISSUE TITLE
Cannot encode POST value retrieved using before_egrep in format expected by Content-Type: application/x-www-form-urlencoded?

### ISSUE THREAD

**Issue by nlykkei** [lanjelot/patator#116]
Consider the following GET request to phpMyAdmin:

`GET http://10.10.10.143/phpmyadmin/index.php HTTP/1.1`

It returns among other hidden input fields the following (`token`):

`<input type="hidden" name="token" value="cUl8&lt;+)~Dh|d&quot;^b9" />`

The browser (percent) encodes this token according to `Content-Type: application/x-www-form-urlencoded` in the POST request (`POST http://10.10.10.143/phpmyadmin/index.php HTTP/1.1`)  as follows:

`set_session=29lmeocho00mgtel0nuo61m2q90e93i4&pma_username=foo&pma_password=bar&server=1&target=index.php&token=cUl8%3C%2B%29%7EDh%7Cd%22%5Eb9`

The problem is that `patator` currently doesn't encode special characters in the token, if `auto_urlencode=0`, and uses invalid encoding (e.g. `token=&JhF%7F%7Bg=&lt=&s5BlGZ9N=`, if `auto_urlencode=1`.

Are there any workarounds?

The `patator` command:

`patator http_fuzz url='http://10.10.10.143/phpmyadmin/index.php' body='set_session=_N1_&pma_username=FILE0&pma_password=foobar&server=1&target=index.php&lang=en&token=_N2_' method=POST follow=1 accept_cookie=1  before_urls='http://10.10.10.143/phpmyadmin/index.php' before_egrep='_N1_:<input type="hidden" name="set_session" value="(\w+)"|_N2_:<input type="hidden" name="token" value="(.+)"' -x ignore:fgrep='Access denied' 0=user.txt 1=passwd.txt persistent=0 auto_urlencode=0 proxy=127.0.0.1:8080 proxy_type=http`

**Comment by nlykkei** [comment]
Hi lanjelot.
Please, say if I somehow can make patator encode the `token` properly? Is there anything wrong with my question/issue?
Thanks.

**Comment by lanjelot** [comment]
I pushed commit 53ace4f which should make your command line work, but you need to remove `auto_urlencode=0`

**Comment by nlykkei** [comment]
Thanks man! So, it was a real bug? Now the code is context aware regarding the encoding, i.e. differentiates between URL encoding of GET-parameters and form-based POST-parameters?

**Comment by nlykkei** [comment]
Thanks man, I will try it out!
