### ISSUE TITLE
Segmentation Fault after updating to the latest version of kali

### ISSUE THREAD

**Issue by rodneymullen3** [lanjelot/patator#123]
For some reason since I upgraded my kali to the latest version of patator it's not working anymore.
Even issuing a simple start command of patator causes it. (so just using command patator)
"Segmentation fault"

Tried fixes: 
-complete reinstall of patator
-using with python 2 and 3 also
-reinstalled my full kali from scratch, upgraded all components, triggered same problem

**Comment by lanjelot** [comment]
Have you using the Vagrantfile?

**Comment by rodneymullen3** [comment]
same problem with patator...
the latest updated killed a lot of appps


Thank You!!

Üdvözlettel(kind regards):
Albert Kuncz

**Comment by rodneymullen3** [comment]
Yep. I think the problem will be with kali and not patator. The latest update killed plenty of apps.

**Comment by mguillau42** [comment]
I've had a Segmentation fault too by just launching `patator` without any arguments using the latest version.
I am not sure that our issues are related because I am running debian unstable and patator was working when launched with python2.

However after an apt upgrade a few days ago the problem has solved itself (but I don't really understand what caused this issue).
If it can help, here are the dependencies of patator which were updated:
```
python3-psycopg2 from 2.8.3-1 to 2.8.3-2
python3 from 3.7.5~rc1-1 to 3.7.5-1
```

**Comment by rodneymullen3** [comment]
> I've had a Segmentation fault too by just launching `patator` without any arguments using the latest version.
> I am not sure that our issues are related because I am running debian unstable and patator was working when launched with python2.
> 
> However after an apt upgrade a few days ago the problem has solved itself (but I don't really understand what caused this issue).
> If it can help, here are the dependencies of patator which were updated:
> 
> ```
> python3-psycopg2 from 2.8.3-1 to 2.8.3-2
> python3 from 3.7.5~rc1-1 to 3.7.5-1
> ```

thank you for the info! I also wasn't able to figure out what caused it. I'll update mine in a second to test it!

**Comment by Kai-Richardson** [comment]
Encountering a similar issue where patator simply won't install on newest kali linux.
```
dpkg: error processing archive /var/cache/apt/archives/patator_0.7-2_all.deb (--unpack):
failed to open package info file '/var/lib/dpkg/tmp.ci/control' for reading: Invalid argument
Errors were encountered while processing: /var/cache/apt/archives/patator_0.7-2_all.deb
E: Sub-process /usr/bin/dpkg returned an error code (1) 
```
