### ISSUE TITLE
Neither port 587 or 465 works for SMTP_LOGIN.

### ISSUE THREAD

**Issue by twinkette** [lanjelot/patator#133]
I am trying to crack my own Outlook account.

I try: `./patator.py smtp_login host=smtp.office365.com user=name@outlook.com password=my_password port=587`

Response: SMTP AUTH extension not supported by server

So I try again with port-465. This time the program just hangs. 

What am I doing wrong? Thanks.

**Comment by lanjelot** [comment]
You haven't enabled SMTP AUTH on your server.

**Comment by lanjelot** [comment]
or if you're a script kiddie then you likely need to pass `starttls=1`
