### ISSUE TITLE
not working i can't understand why

### ISSUE THREAD

**Issue by mayomacam** [lanjelot/patator#136]
└──╼ $patator ldap_login user=fsmith password=FILE0 0=Password.txt host=10.10.10.175 -x ignore:fgrep!='Access denied for user'
19:53:07 patator    INFO - Starting Patator v0.7 (https://github.com/lanjelot/patator) at 2020-06-17 19:53 IST
Process Producer:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/bin/patator", line 1700, in produce
    for _ in f:
  File "/usr/lib/python3.8/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf1 in position 933: invalid continuation byte

After that it stop working.

**Comment by LivelyCarpet87** [comment]
I'm not sure if this is the right solution, but I would generally check the encoding of the .txt file. My guess that Patator struggles with some encoding formats.

**Comment by lanjelot** [comment]
@mayomacam can you please try with latest version and report back? Cheers

**Comment by mayomacam** [comment]
I am not getting any error likes before but it doesn't take user as a input and give error to it.
![Screenshot at 2020-06-18 19-39-34](https://user-images.githubusercontent.com/38097361/85032247-2052b980-b16f-11ea-9627-ba968d7fbd34.png)

I have try removing user and try but 
![Screenshot at 2020-06-18 19-53-38](https://user-images.githubusercontent.com/38097361/85032949-e9c96e80-b16f-11ea-9224-9a7ad3f2d4a5.png)

Not gonna work without user it's already known.

**Comment by lanjelot** [comment]
Your binddn should target specific user entries and so it should look something like binddn="uid=jsmith,CN=users,..." 
I am giving the uid attribute as an example here, you should look for yourself what you actually need. Ok i'm closing this as this no longer Patator-related.
