### ISSUE TITLE
oracle_login module isn't working in macOS

### ISSUE THREAD

**Issue by ritsulin** [lanjelot/patator#137]
It seems that oracle_login module is not working in macOS, the msg is [Cx_Oracle.DatabaseError: DPI-1047: 64-Bit Oracle Client Library Cannot Be Loaded: “Dlopen(Libclntsh.dylib, 1): Image Not Found”].
Like this:
![Imgur](https://i.imgur.com/Eitr2Pm.png)

**Comment by lanjelot** [comment]
Looks like an issue with your env, not patator. Try the Dockerfile or the Vagrantfile, they both properly install cx_oracle
