### ISSUE TITLE
http_fuzz + add brute multipart/form-data authentication

### ISSUE THREAD

**Issue by Porol** [lanjelot/patator#14]
Hi,
Suggestions for future versions.
Please add brute "multipart/form-data" support to this script.
Usual method=POST sends enctype="application/x-www-form-urlencoded"
Encountered form with method=POST sends enctype="multipart/form-data"
Example form:

form enctype="multipart/form-data" method="post" action="/login.cgi">
input type="text" name="user" />
input type="password" name="pass" />
input type="submit" value="Login" />
/form>

work request:=========================
POST /login.cgi HTTP/1.1
Host: 127.0.0.1
Content-Type: multipart/form-data; boundary=123
Content-Length: 142

--123
Content-Disposition: form-data; name="user"

root
--123
Content-Disposition: form-data; name="pass"

rootpass
--123--
work request:=========================

response 200 Ok - if not valid pair user/pass
response 302 Found - if valid pair user/pass

I think in patator syntax make as simple POST with an additional option, conditionally "--multipart":

http_fuzz url=https://127.0.0.1/login.cgi method=POST --multipart body='user=root&pass=FILE0' ...

**Comment by lanjelot** [comment]
You can already do that:
```
$ cat > blah.txt <<'EOF'
> --123
> Content-Disposition: form-data; name="user"
> 
> root
> --123
> Content-Disposition: form-data; name="pass"
> 
> FILE0
> --123--
> EOF
$ http_fuzz url=https://127.0.0.1/login.cgi method=POST header=@<(echo -e 'Content-Type: multipart/form-data; boundary=123\nUser-Agent: RTFM') body=@blah.txt auto_urlencode=0 0=passwords.txt
```
