### ISSUE TITLE
[Feature Request] Progress Indicator

### ISSUE THREAD

**Issue by TrevorRuppert** [lanjelot/patator#142]
I just started using Patator vs Hydra recently for the JSON fuzzing and the ability to specify a custom Content-Type header but the one thing I would love to see is a progress indicator even something as simple as a current index/total indexes which is something I have come to miss from Hydra. If you could implement that I would love you forever (I do plan on making a pull request to see if I can implement this myself at some point this week).

**Comment by lanjelot** [comment]
Have you tried pressing Enter during execution? More info at https://github.com/lanjelot/patator/blob/master/patator.py#L100 ?

**Comment by TrevorRuppert** [comment]
I did not try that but I did now and it works like a charm. With that option being there with the values already needed it should be trivial to simply change the output for the current index to include the max value so I will make a pull for that tomorrow and take a crack at it. Thank you for the super fast response.

**Comment by lanjelot** [comment]
The max value is already included. I'm not sure I understand what you're wanting to have shown in the Progress status line. Maybe you could give a full example here first.

**Comment by TrevorRuppert** [comment]
what I mean is currently on each request it tells you the details about each request such as the code, candidate, and num, in the num field I think it would be beneficial to have it be num/max. similar to how if you hit space it tells you progress: % (num/max) just move the num/max portion to the live output instead of having to give input prior.

**Comment by lanjelot** [comment]
hum I'm not too keen so far because it's gonna make the num column much wider
