### ISSUE TITLE
HTTP_FUZZ Error -  PY_SSIZE_T_CLEAN will be required for '#'

### ISSUE THREAD

**Issue by ellosys** [lanjelot/patator#144]
lhost&Password=FILE0" method=POST scheme=http follow=1 0=wordlist.txt -x ignore:fgrep='user name or password was entered incorrectly.' accept_cookie=1
00:22:56 patator    INFO - Starting Patator 0.9 (https://github.com/lanjelot/patator) with python-3.8.5 at 2020-08-02 00:22 +03
00:22:56 patator    INFO -                                                                              
00:22:56 patator    INFO - code size:clen       time | candidate                          |   num | mesg
00:22:56 patator    INFO - -----------------------------------------------------------------------------
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()
patator.py:3872: DeprecationWarning: PY_SSIZE_T_CLEAN will be required for '#' formats
  fp.perform()

**Comment by lanjelot** [comment]
What version of pycurl are you using? You can run `pip list | grep curl` to find out. This warning was fixed in latest pycurl version according to https://github.com/pycurl/pycurl/pull/600
