### ISSUE TITLE
Can't load text files that customize the target IP and define the port?

### ISSUE THREAD

**Issue by qinggegeya** [lanjelot/patator#146]
Suppose I now want to crack the SSH password for these three IPs:
`10.0.0.1:22
10.0.0.2:23
10.0.0.3:24`
Can't you batch brute force by loading text?

**Comment by lanjelot** [comment]
Use the COMBO keyword.

**Comment by qinggegeya** [comment]
> Use the COMBO keyword.

learning...thanks，I find the patator It's a little complicated but it's functional.good.
