### ISSUE TITLE
do  not try  other  passwords on  "200 OK"

### ISSUE THREAD

**Issue by gudge25** [lanjelot/patator#147]
Greeting 
is there a  way to end testing on a  host if i get  successful reply  "200 OK"
Regards

**Comment by LivelyCarpet87** [comment]
try the -x actions with the condition code=200

**Comment by LivelyCarpet87** [comment]
'-x free=user:code=200' should stop testing for a user once there is a 200 ok. I'm not sure if you could use it for hosts. Maybe you could bodge it and reverse the user/host wordlists.

**Comment by lanjelot** [comment]
yes `-x free=host:code=200` should work. However with `http_fuzz` you need to pass `host` instead of `url` like for example: `./patator.py http_fuzz scheme=https host=localhost path=/RANGE0 0=int:1-10 -t 1 -x free=host:code=200`
