### ISSUE TITLE
Globbing support for the -x ignore:code http switch

### ISSUE THREAD

**Issue by maaaaz** [lanjelot/patator#15]
Hello,

As we sometimes need to ignore a lot of HTTP response code, would it be possible to have the `ignore:code` option support a globbing parameter, like for instance a `ignore:code=40*` to ignore all 40x codes ?

I don't know if it is relevant for all modules supporting the `code` directive.

Thank you.

**Comment by lanjelot** [comment]
Why not, this should be as easy as this patch:
```
   def match_code(self, val):
-    return val == str(self.code)
+    return re.match('%s$' % val, str(self.code))
```

In the meantime though you could just pass `-x ignore:egrep='HTTP/1\.0 40.` to ignore all 40x codes.

**Comment by maaaaz** [comment]
Great.
Do you think that it would be cool to also accept a list of codes, like `-x ignore:code=40*,30*` instead of passing multiple `ignore` params ?

**Comment by lanjelot** [comment]
Since 0b2ad0dc5e590456043a6cc5f57ae27711edcd87 you can now pass things like -x ignore:code=40[13] or -x ignore:code='40.|30.'

**Comment by maaaaz** [comment]
Cool !
Thank you.
