### ISSUE TITLE
<class 'TypeError'> ord() expected string of length 1, but int found

### ISSUE THREAD

**Issue by scubahalo** [lanjelot/patator#150]
I'm getting this error under the "mesg" column when running the mssql_login module:

<class 'TypeError'> ord() expected string of length 1, but int found

I figured it was a Python version issue so I used pyenv to run it under the recommended 3.6.0 and I still get the same issue.

**Comment by lanjelot** [comment]
can you try with the Docker patator version. And also can you please paste the command line and console output ?

**Comment by scubahalo** [comment]
Here's the command line and console output:
![patator_test](https://user-images.githubusercontent.com/74792984/100168903-03858500-2e77-11eb-975b-b7ee55ab73ab.png)
I'm not sure why it says it's running Python 3.8.5 when I've got the shell set to 3.6.0 with pyenv. That might be the issue. I've tried several different versions of Python and it does the same thing as above. Maybe it's overriding the pyenv setting somehow?

So far I haven't been able to get your Dockerfile to run in my Kali VM. I'm not very familiar with Docker so more than likely it's operator error. I'll keep trying though.

**Comment by lanjelot** [comment]
can you post the output of `pip list` please? Maybe you're using an old `impacket` version

**Comment by scubahalo** [comment]
Here you go:
![impacket_vers](https://user-images.githubusercontent.com/74792984/100316560-9e618a80-2f6f-11eb-8f64-d54bdfb84419.png)
Thanks for the Docker commands - that's a big help. I'll try it tomorrow morning.

**Comment by scubahalo** [comment]
Tried Docker again. Patator can't find the target. Do I need to assign a port to the container?
![patator_test](https://user-images.githubusercontent.com/74792984/100491657-527f2480-30da-11eb-8c84-ac5d4128bd2d.png)

**Comment by lanjelot** [comment]
Your pb now is that the wordlist is on your host and patator can't access it because it is running inside the container. Try:
```
git clone https://github.com/danielmiessler/SecLists.git
docker run -it --rm -v $PWD/SecLists:/SecLists patator mssql_login host=10.11.1.13 user=sa password=FILE0 0=/SecLists/Passwords/mssql-passwords-nansh0u-guardicore.txt -x ignore:fgrep='Login failed'
```

**Comment by scubahalo** [comment]
Okay, it's working now. That possibility did cross my mind, but I didn't know how to point patator to it. Now I do. Thanks! BTW, did you figure out why the original error occurs? Just curious.

**Comment by lanjelot** [comment]
Your env was the pb. You welcome. :)
