### ISSUE TITLE
Use libmariadb-dev instead of libmariadbclient-dev

### ISSUE THREAD

**Issue by ottok** [lanjelot/patator#151]
Hello!

Your current [Docker and Vagrantfile use libmariadbclient-dev](https://github.com/lanjelot/patator/search?q=libmariadbclient-dev). This is fine for Ubuntu 18.04, but in the future you should change those to [libmariadb-dev](https://packages.debian.org/search?keywords=libmariadb-dev) (or libmariadb-dev-compat if you need to build something old that does not find the correct soname otherwise).

**Comment by lanjelot** [comment]
thx for the tip
