### ISSUE TITLE
Requirements txt forgeted library 

### ISSUE THREAD

**Issue by hithmast** [lanjelot/patator#152]
pysqlcipher3 is missid from your requirements.txt file i got an error 
ERROR: 
In file included from src/python2/module.c:24:
src/python2/connection.h:26:10: fatal error: Python.h: No such file or directory
   26 | #include "Python.h"
      |          ^~~~~~~~~~
compilation terminated.
No eggs found in /tmp/easy_install-pSjo4B/pysqlcipher3-1.0.3/egg-dist-tmp-44qRi_ (setup script problem?)
error: The 'pysqlcipher3' distribution was not found and is required by patator

**Comment by lanjelot** [comment]
no this is because you need `python-devel`. Please have a look at  the Dockerfile or Vagrantfile files

**Comment by hithmast** [comment]
dn
