### ISSUE TITLE
Installation failure: No sqlite3.h is missing

### ISSUE THREAD

**Issue by machinexa2** [lanjelot/patator#155]
running install
running bdist_egg
running egg_info
writing patator.egg-info/PKG-INFO
writing dependency_links to patator.egg-info/dependency_links.txt
writing requirements to patator.egg-info/requires.txt
writing top-level names to patator.egg-info/top_level.txt
reading manifest file 'patator.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'patator.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
warning: install_lib: 'build/lib' does not exist -- no Python modules to install

creating build/bdist.linux-x86_64/egg
creating build/bdist.linux-x86_64/egg/EGG-INFO
installing scripts to build/bdist.linux-x86_64/egg/EGG-INFO/scripts
running install_scripts
running build_scripts
creating build/bdist.linux-x86_64/egg/EGG-INFO/scripts
copying build/scripts-3.9/patator.py -> build/bdist.linux-x86_64/egg/EGG-INFO/scripts
changing mode of build/bdist.linux-x86_64/egg/EGG-INFO/scripts/patator.py to 755
copying patator.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying patator.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying patator.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying patator.egg-info/requires.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying patator.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
zip_safe flag not set; analyzing archive contents...
creating 'dist/patator-0.9-py3.9.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing patator-0.9-py3.9.egg
Removing /usr/local/lib/python3.9/dist-packages/patator-0.9-py3.9.egg
Copying patator-0.9-py3.9.egg to /usr/local/lib/python3.9/dist-packages
patator 0.9 is already the active version in easy-install.pth
Installing patator.py script to /usr/local/bin

Installed /usr/local/lib/python3.9/dist-packages/patator-0.9-py3.9.egg
Processing dependencies for patator==0.9
Searching for pysqlcipher3
Reading https://pypi.org/simple/pysqlcipher3/
Downloading https://files.pythonhosted.org/packages/a4/06/1d56bdec3129eff6dd54323d249784ccd90ce03c8cae7870d45e434bae77/pysqlcipher3-1.0.3.tar.gz#sha256=694e5bbb6ece8a064bd55f261e54b9ffbb3af1784afdc4dce4948a0251a8a430
Best match: pysqlcipher3 1.0.3
Processing pysqlcipher3-1.0.3.tar.gz
Writing /tmp/easy_install-iwqc2xlr/pysqlcipher3-1.0.3/setup.cfg
Running pysqlcipher3-1.0.3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-iwqc2xlr/pysqlcipher3-1.0.3/egg-dist-tmp-bqx_gfnc
warning: no previously-included files matching '*~' found anywhere in distribution
warning: no previously-included files matching '*.pyc' found anywhere in distribution
In file included from src/python3/connection.c:27:
src/python3/connection.h:33:10: fatal error: sqlcipher/sqlite3.h: No such file or directory
   33 | #include "sqlcipher/sqlite3.h"
      |          ^~~~~~~~~~~~~~~~~~~~~
compilation terminated.
No eggs found in /tmp/easy_install-iwqc2xlr/pysqlcipher3-1.0.3/egg-dist-tmp-bqx_gfnc (setup script problem?)
error: The 'pysqlcipher3' distribution was not found and is required by patator

Python3 version:  3.9.1
GCC Version: 10.2.0

Tried `apt install sqlcipher libsqlite3-dev` but still failed.
```
root@kali:/tmp/potato# apt install libsqlite3-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libsqlite3-dev is already the newest version (3.34.1-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:/tmp/potato# apt install sqlcipher 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
sqlcipher is already the newest version (3.4.1-2).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
root@kali:/tmp/potato# 
```

**Comment by lanjelot** [comment]
the error says `error: The 'pysqlcipher3' distribution was not found and is required by patator`
