### ISSUE TITLE
Encoding issue with http_fuzz

### ISSUE THREAD

**Issue by h4knet** [lanjelot/patator#156]
Hello,
I've encountered an issue with **http_fuzz** mode as it seems to re-encode the body parameter when a file is given.

Here is an example given to deal with `form-data` forms given by @lanjelot :
```
$ cat > blah.txt <<'EOF'
> --123
> Content-Disposition: form-data; name="user"
> 
> root
> --123
> Content-Disposition: form-data; name="pass"
> 
> FILE0
> --123--
> EOF
$ http_fuzz url=https://127.0.0.1/login.cgi method=POST header=@<(echo -e 'Content-Type: multipart/form-data; boundary=123\nUser-Agent: RTFM') body=@blah.txt auto_urlencode=0 0=passwords.txt
```
_Originally posted by @lanjelot in https://github.com/lanjelot/patator/issues/14#issuecomment-102264426_

The issue I encounter can be seen in Burp as patator seems to strip the `\r` characters even with `auto_urlencode` set to 0 :
![image](https://user-images.githubusercontent.com/1595901/106593328-f8bf2e80-6550-11eb-9087-61ac67e05b47.png)

Here is the source file used with \r\n characters:
![image](https://user-images.githubusercontent.com/1595901/106593622-53f12100-6551-11eb-9790-5b25110eb8e2.png)

As a result the backend server do not process the request as intended.

The command I used: 
`patator http_fuzz url="https://XXX/api/1/user/login" method=POST auto_urlencode=0 body=@login-form.txt header="Content-Type: multipart/form-data; boundary=1337"`

**Comment by lanjelot** [comment]
great bug report, thx!
