### ISSUE TITLE
While installing via dockerfile, at line "RUN python3 -m pip install -r requirements.txt" there was error.

### ISSUE THREAD

**Issue by aoe1928** [lanjelot/patator#162]
While installing via dockerfile, at line `RUN python3 -m pip install -r requirements.txt` there was error, "No module named 'setuptools_rust'" and the installation stopped.
I added`RUN python3 -m pip install --upgrade pip` and it worked. I think if the pip libraries were too old, you can't install.

**Comment by Jarekwidzew77** [comment]
> I added`RUN python3 -m pip install --upgrade pip`

Hello . where should  i add this  line to avoid  this issue

**Comment by aoe1928** [comment]
Change the 49th line of the Dockerfile
```
WORKDIR /opt/patator
COPY ./requirements.txt ./
RUN python3 -m pip install -r requirements.txt
```

to

```
WORKDIR /opt/patator
COPY ./requirements.txt ./
RUN python3 -m pip install --upgrade pip
RUN python3 -m pip install -r requirements.txt
```

and it should work.

**Comment by Jarekwidzew77** [comment]
Thank you so much .Its working !!!!. Thank you again.
