### ISSUE TITLE
Add --max_password_length to ignore longer passwords

### ISSUE THREAD

**Issue by larsen0815** [lanjelot/patator#166]
Some sites allow only a fixed number of characters for a password, while the password lists may contain many that are longer than that (currently have a login where it's limited to 7 characters).

I had to remove longer passwords from the lists like this
````
perl -lne 'length($_) < 8 && print' 2020-200_most_used_passwords.txt > out.txt
````

Would be helpful if patator could be configured to automatically don't try passwords that are longer than the configured limit.

**Comment by lanjelot** [comment]
Maybe use the PROG keyword :
```
./patator.py dummy_test data=PROG0 0='cut -c -8 /mnt/SecLists/Passwords/richelieu-french-top5000.txt'
```
