### ISSUE TITLE
Installing on a mac giving me versioning issues?

### ISSUE THREAD

**Issue by S3j5b0** [lanjelot/patator#168]
I'm trying to install patator on my mac machine, needing it for a projectdoing some cracking.

So, I first attempted installing though pip:

```
    pip3 install patator
This fails with:

        ----------------------------------------
    WARNING: Discarding https://files.pythonhosted.org/packages/6a/91/bdfe808fb5dc99a5f65833b370818161b77ef6d1e19b488e4c146ab615aa/mysqlclient-1.3.0.tar.gz#sha256=06eb5664e3738b283ea2262ee60ed83192e898f019cc7ff251f4d05a564ab3b7 (from https://pypi.org/simple/mysqlclient/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
    Collecting patator
      Using cached patator-0.8-py3-none-any.whl (51 kB)
      Using cached patator-0.7-py2.py3-none-any.whl (45 kB)
    Collecting psycopg2
      Downloading psycopg2-2.9.1.tar.gz (379 kB)
         |████████████████████████████████| 379 kB 3.3 MB/s 
    ERROR: Cannot install patator==0.7, patator==0.8 and patator==0.9 because these package versions have conflicting dependencies.
    
    The conflict is caused by:
        patator 0.9 depends on mysqlclient
        patator 0.8 depends on mysqlclient
        patator 0.7 depends on mysqlclient
    
```
    To fix this you could try to:
    1. loosen the range of package versions you've specified
    2. remove package versions to allow pip attempt to solve the dependency conflict
    
    ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies'

It's giving me two tips that I should not specify the package versions, but this is confusing to me, since I am not specifying any versions at all?

I also tried visiting the link that it gives me, but there's really no help at all there.

What's happening here? Why am I not able to install patator?

**Comment by lanjelot** [comment]
follow https://github.com/lanjelot/patator/blob/master/README.md#install
