### ISSUE TITLE
PycURL empty resolver throws an error

### ISSUE THREAD

**Issue by paivao** [lanjelot/patator#170]
Greetings,

While using patator, I checked that an empty resolve triggers an exception in PycURL...

https://github.com/lanjelot/patator/blob/e48316728feee534e688adbd42b6b9bf9282eb2f/patator.py#L3962

Locally, I patched the code to set the option only if resolve is set, and worked.
This is the snippet:

```python
if resolve:
  fp.setopt(pycurl.RESOLVE, [resolve])
```

**Comment by lanjelot** [comment]
thanks but this was fixed ages ago

**Comment by lanjelot** [comment]
i cant reproduce
