### ISSUE TITLE
http_fuzz module giving <class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''!")

### ISSUE THREAD

**Issue by 0xGreen** [lanjelot/patator#174]
Hi,
http_fuzz module is giving "<class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''!")" error for all payloads.

```bash
patator http_fuzz url=http://127.0.0.1:8000/FILE0 0=test.txt
```

```bash
23:07:04 patator    INFO - Starting Patator 0.9 (https://github.com/lanjelot/patator) with python-3.9.9 at 2022-01-12 23:07 EST
23:07:04 patator    INFO -                                                                              
23:07:04 patator    INFO - code size:clen       time | candidate                          |   num | mesg
23:07:04 patator    INFO - -----------------------------------------------------------------------------
23:07:06 patator    FAIL - xxx  71:-1          1.015 | root                               |     1 | <class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''!")
23:07:06 patator    FAIL - xxx  71:-1          1.014 | admin                              |     2 | <class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''!")
23:07:06 patator    FAIL - xxx  71:-1          1.014 | guest                              |     3 | <class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''!")
23:07:06 patator    INFO - Hits/Done/Skip/Fail/Size: 0/3/0/3/3, Avg: 1 r/s, Time: 0h 0m 2s
```

I have tried both the kali version and the github version.

Other module like smb_login, ftp_login are working fine.

Any suggestions?

Thanks!

**Comment by Pernat1y** [comment]
Looks like something wrong with 'resolve' attribute in here:
https://github.com/lanjelot/patator/blob/master/patator.py#L3965

**Comment by maggick** [comment]
Quick and dirty fix: Just comment the line `fp.setopt(pycurl.RESOLVE, [resolve])`
→ `# fp.setopt(pycurl.RESOLVE, [resolve])`

**Comment by 0xGreen** [comment]
Thanks!! 

Yes this solution works, but i was wondering if the developer can provide a more appropriate solution.

**Comment by font-deny** [comment]
For those still using a version that doesn't have the fix (e.g. 0.9), the workaround is to specify `resolve`, e.g. a dummy `resolve=target:127.0.0.1`.
