### ISSUE TITLE
IKE Module Does Not Support Input List

### ISSUE THREAD

**Issue by Zamanry** [lanjelot/patator#179]
The command I typically run for a single host is:
```
sudo python 'patator/patator.py' ike_enum host=#.#.#.# transform=MOD0 0=TRANS aggressive=RANGE1 1=int:0-1 --csv='Patator_IKE_#.#.#.#.csv'
```
However, changing this to be the following also fails. It will only run the first IP address only and the end:
```
sudo python 'patator/patator.py' ike_enum host=FILE0 0='IKE_Targets.txt' transform=MOD1 1=TRANS aggressive=RANGE2 2=int:0-1 --csv='Patator_IKE_#.#.#.#.csv'
```

I would like the IKE module to support an input hosts file like the other modules.

**Comment by lanjelot** [comment]
your command line seems correct, it should work, not sure what is going wrong but i suspect a user error :)
Try to `sudo -s` first and then run that command line and make sure `IKE_Targets.txt` is in your working directory

**Comment by lanjelot** [comment]
Your command line looks correct so I am not sure what is going wrong but i suspect a user error :)
Try to `sudo -s` first and then run that command line and make sure `IKE_Targets.txt` is in your working directory.
