### ISSUE TITLE
IKE Module CSV Output Only Prints Hostname, not IP Address

### ISSUE THREAD

**Issue by Zamanry** [lanjelot/patator#180]
If you run the following command against an IP address and not a hostname, the output CSV will not print out the IP address.
```
sudo python 'patator/patator.py' ike_enum host=#.#.#.# transform=MOD0 0=TRANS aggressive=RANGE1 1=int:0-1 --csv='Patator_IKE_#.#.#.#.csv'
```
If a hostname was provided, the hostname will be provided. This defeats the purpose of the output CSV combined file and creates confusion. As a work around, I have just been adding the IP address to the name of each CSV file instead. This is inconsistent with the other modules.

**Comment by lanjelot** [comment]
not a bug, only candidates are saved to output file.
