### ISSUE TITLE
<class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry

### ISSUE THREAD

**Issue by carouselcarousel** [lanjelot/patator#191]
Warnign message:
/usr/bin/patator:2601: DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13
  from telnetlib import Telnet
  
  For every entry I get this error:
  <class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''")

Using the latest version of patator: "patator is already the newest version (0.9-3)."
using the latest pycurl: "Requirement already satisfied: pycurl in /usr/lib/python3/dist-packages (7.45.2)"

**Comment by LittleAunt** [comment]
I have the same problem!!!

**Comment by carouselcarousel** [comment]
workaround. use the windows exe.
https://github.com/maaaaz/patator-windows/archive/master.zip

**Comment by lanjelot** [comment]
duplicate of #195
