### ISSUE TITLE
Cmake requires 3.13

### ISSUE THREAD

**Issue by Dastano** [lanjelot/patator#192]
**Describe the bug**
Cmake now requires 3.13 because of FreeRDP

Current fix is, to go back of an old Build of FreeRDP:

RUN git clone -n https://github.com/FreeRDP/FreeRDP/ . && git checkout 03d4f6a3225b7a5baa5afe1e12e1bb55c044fb79 .

**Comment by gdudek** [comment]
Using the older FreeRDP also fixes an issue with fuse/fuse3 compatibility
