### ISSUE TITLE
Error <class 'pycurl.error'>

### ISSUE THREAD

**Issue by indeqs** [lanjelot/patator#195]
I get the error: <class 'pycurl.error'> (49, "Couldn't parse CURLOPT_RESOLVE entry ''")
everytime I try bruteforcing :)

patator version: 0.9 with python-3.9.2

**Comment by carouselcarousel** [comment]
many people have this problem. I just changed to a different fuzzer because wasn't unable to fix it.

**Comment by gildasio** [comment]
Just inform the option `resolve`:

```
http_fuzz ... resolve=domain:ipaddr
```

**Comment by lanjelot** [comment]
this was fixed in git, or will be in next release after 0.9

**Comment by kali-mx** [comment]
> Just inform the option `resolve`:
> 
> ```
> http_fuzz ... resolve=domain:ipaddr
> ```

Thanks gildasio.  This is a valid solution, and just wanted to make it clearer to newbies. This works as expected in Kali, installing patator with `apt install patator`. See example below for exact syntax for the `resolve` argument usage:

```ruby
~/THM/BruteForceHeros patator http_fuzz resolve=domain:10.10.123.241 method=POST timeout=10 url="http://10.10.123.241/login.php" 0=passwords.txt body="username=admin&password=FILE0&Login=Login&user_token=${CSRF}" header="Cookie: PHPSESSID=${SESSIONID}; security=impossible" -x ignore:fgrep='Location: login.php' --thread=64
```
