### ISSUE TITLE
telnetlib will be removed in Python 3.13

### ISSUE THREAD

**Issue by carlsmedstad** [lanjelot/patator#198]
Hey :wave:

I maintain the [Arch User Repository package](https://aur.archlinux.org/packages/patator) for patator.

The library `telnetlib` will be removed from the stdlib in Python 3.13 which will be released in approximately a year. Would it be possible to remove it as a dependency from patator and make new release to avoid us having to patch the project?

```python
/bin/smtp_login:2601: DeprecationWarning: 'telnetlib' is deprecated and slated for removal in Python 3.13
  from telnetlib import Telnet
```

Much appreciated!

**Comment by Shasheen8** [comment]
Hello, 

Is there an update on this issue? It looks like it has not been updated within the repo yet. 

Thanks
