### ISSUE TITLE
Building standalone exe for WIndows

### ISSUE THREAD

**Issue by Laggii** [lanjelot/patator#20]
Followed the short guide in Readme for making an *exe for windows machines. I met no errors while compiling however the compiled exe doesnt work. 

When I am trying to do patator.exe -h or patator.exe ssh_login the console prints nothing. No errors, no crashes.

I tried to compile on 2 machines: Windows 8 and Windows XP, both same result.
Any ideas what to do now?

Thanks.

**Comment by maaaaz** [comment]
I'm experiencing the same trouble. I don't know how to debug that.

**Comment by maaaaz** [comment]
So, I managed to debug it and found that there are some issues with the **MSSQL part**, especially the `from impacket import tds` instruction. I really don't know why.

Anyway you can get a working windows executable by replacing the line #4488:
* from:
```
'mssql_login', (Controller, MSSQL_login))
```
* to:
```
'mssql_login', (Controller, None))
```
By the way I'm distributing a [working Windows version](https://github.com/maaaaz/patator-windows).

Cheers.

**Comment by lanjelot** [comment]
No pb. Thanks for looking into this issue.

**Comment by maaaaz** [comment]
Cool :) If you even want to put a link to the Windows version in your README it would be even cooler!
