### ISSUE TITLE
Pull access denied?

### ISSUE THREAD

**Issue by axxic3** [lanjelot/patator#210]
While running the initial command from the github readme, I get this error:

`sudo docker run -it --rm -v $PWD/SecLists/Passwords:/mnt patator dummy_test data=FILE0 0=/mnt/richelieu-french-top5000.txt`

```
Unable to find image 'patator:latest' locally
docker: Error response from daemon: pull access denied for patator, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
```

Has the name of the docker image changed? If so, how would I force this command to use the new name?

**Comment by mlec1** [comment]
The official one is this one I think https://hub.docker.com/r/lanjelot/patator

You can also build it locally with the dockerfile
