### ISSUE TITLE
patator issue Kali 2.0

### ISSUE THREAD

**Issue by kofx** [lanjelot/patator#28]
hi i had this issue with patator on  kali 2.0 

Traceback (most recent call last):
  File "/usr/bin/patator", line 3755, in <module>
    powder = ctrl(module, [name] + argv[1:])
  File "/usr/bin/patator", line 1032, in __init__
    for k, v in self.expand_key(arg):
ValueError: need more than 1 value to unpack

**Comment by SingularBunny** [comment]
There is because you make a some mistake in initialization string. Please, provide it.

**Comment by kofx** [comment]
Hi , thank you for the reply , please excuse me yeah it's my fault  false "host:" true "host="

patator ssh_login host:host user=root password=FILE0 0=password.txt -x ignore:mesg='Authentication failed.'

this is the mistake 
sorry again
