### ISSUE TITLE
Provide a requirements.txt for essential dependencies

### ISSUE THREAD

**Issue by maaaaz** [lanjelot/patator#31]
Hello @lanjelot,

It would be cool that you provide a `requirements.txt` file with essential dependencies (no cx_Oracle or whatsoever) for patator to run.

Cheers.

**Comment by noraj1337** [comment]
Archlinux:

```
# pacman -S python2-pyopenssl python2-paramiko python2-ipy python2-dnspython python2-pysnmp python2-pycurl
# pip2 install impacket pycrypto
```

But yes the install process sucks, patator could be provided as an PyPi package.

**Comment by maaaaz** [comment]
@noraj1337 +1
