### ISSUE TITLE
Crash in before_egrep functionality of http_fuzz module

### ISSUE THREAD

**Issue by JonasMoennig** [lanjelot/patator#32]
When using the before_egrep option, patator crashes if the specified regex is not found, because "group()" is called on the result of the regex match without checking whether the result is None.
Just inserting an if-statement at this place was not sufficient to solve the problem.

**Comment by lanjelot** [comment]
Thanks for reporting. Any chance you'd be able to submit a patch?

**Comment by lanjelot** [comment]
If the regex doesn't match, then an exception will be thrown by the module and the controller will try again. I don't see why you would want a check before group() is called, can you please expand? Like do you want to use a default value when the regex doesn't match or something?
