### ISSUE TITLE
'exceptions.AttributeError'> 'module' object has no attribute 'PRIMARY_PORT' in http_fuzz module

### ISSUE THREAD

**Issue by NullArray** [lanjelot/patator#36]
When i run patator with these arguments it's giving me the error message displayed in the title of this post in the "message" part of the printed text in my terminal.

`patator.py http_fuzz url=http://example.org/admin/index.php method=POST body="log=administrator&pwd=FILE0&wp-submit=Log+In&redirect_to=http%3A%2F%2Fexample.org%2Fwp-admin%2F&testcookie=1" 0=C:\passwords.txt`

Don't know what's up with that, any light you could shed on the issue would be greatly appreciated.

**Comment by lanjelot** [comment]
I've got no idea either mate, did you manage to find out what was going wrong?

**Comment by rafalokaum** [comment]
I have same problem.. lanje my lov 
 
/patator.py http_fuzz url=http://167.114.xxx.xxx/phpmyadmin/index.php method=POST body='pma_username=FILE0&pma_password=FILE1&server=1&target=index.php&lang=en&token=' 0=/username.txt 1=/rockyou.txt before_urls=http://167.114.xxx.xxx/phpmyadmin/index.php accept_cookie=1 follow=1 -x ignore:fgrep='#1045 Cannot log in to the MySQL server' -l /tmp/qsdf


and i have this error message 

18:39:30 patator    FAIL - xxx  82:-1          3.994 | admin:123456                       |     1 | <type 'exceptions.AttributeError'> 'module' object has no attribute 'PRIMARY_PORT'

**Comment by NullArray** [comment]
At least now we know it can be replicated, in any event i haven't looked through any of the code 1. Because i am notoriously lazy and 2. I figured the dev would be far more familiar with his own code anyhow.  But let's see.

So the first occurence of PRIMARY_PORT  in my version of patator is in the method of the http_fuzz class called perform_fp at line line 3556:

```target['port'] = fp.getinfo(pycurl.PRIMARY_PORT)```

So if the error message is to be believed(and somehow the text that's printed to the terminal gets parsed all goofy for one reason or another) the pycurl module on which patator is dependent doesn't have an attribute called PRIMARY_PORT, which it should have.  Turns out i was using pycurl-7.19.0.2 i have since upgraded to pycurl-7.43.0 i hope it was just a bug in the old version of pycurl but i'll know for sure after i give it a test run.

**Comment by lanjelot** [comment]
Sounds like most likely you were using an old version of pycurl that didnt have PRIMARY_PORT.

**Comment by dzhusi** [comment]
I have the same problem. Using libcurl/7.43.0 SecureTransport zlib/1.2.5

**Comment by lanjelot** [comment]
guys -> https://github.com/pycurl/pycurl/blob/master/ChangeLog#L378
