### ISSUE TITLE
Memory Consumption

### ISSUE THREAD

**Issue by EverythingTxyz** [lanjelot/patator#37]
Not sure if this is a true issue, but this thing seems to be hogging more and more memory the longer it runs. On an ubuntu 14 LTS system I can sit and watch the memory climb.

Anyone else have this issue or know of a fix?

Will it max out on how much memory it wants or will it go until my system crashes? only time will tell I guess.

Issue is occurring with ssh brute force and a 13GB word list.

**Comment by lanjelot** [comment]
How did you go? Did Patator crash your system? Can you provide more information with regards to the memory usage etc.

**Comment by SingularBunny** [comment]
This can occur because in method `produce` on consumer queues uses `.put_nowait(prod)`. Queues defined as infinite. And if the producer generates as many objects that the consumers can not process them memory overflows.

**Comment by EverythingTxyz** [comment]
I ended up using something else.

**Comment by lanjelot** [comment]
I used to have maxsizes on the queues before, not sure why i didn't keep them when i switched to multiprocesses. Commit 142d48c should fix this.
