### ISSUE TITLE
Recursive mode for http_fuzz

### ISSUE THREAD

**Issue by maaaaz** [lanjelot/patator#38]
Hey @lanjelot,
Would you be kind enough to add a recursive mode for bruteforcing URL with `http_fuzz` ?

Cheers !

**Comment by lanjelot** [comment]
Patator's design will not allow this to be easily implemented I don't think. Plus I'm not sold on the idea as I don't see the point of automatically wfuzz'ing into images/ and js/ directories. Patches are always welcome though...

**Comment by maaaaz** [comment]
Ok :(
I think that obviously, this option wouldn't be enabled by default and should only be **left to the user's experience**: of course it's silly to bf `/images/` and `/js/` but recursivity would be great for applicative dirs.
