### ISSUE TITLE
Set diferent port on http_fuzz (other than 80)

### ISSUE THREAD

**Issue by w1r3dh4ck3r** [lanjelot/patator#43]
How do I set the port to a different port, other than the 80? my Mikrotik runs in another port (the web interface I mean, I guess I could change it, but just asking, is there such a option?

**Comment by lanjelot** [comment]
http_fuzz url=http://blah:1234/

**Comment by w1r3dh4ck3r** [comment]
thanks, I had tried that, for some reason it did not work, I looked at the
code and the port parameter for http was commented out, but none of that is
going to work on my router, which is good, but I feel like I'm missing
something here, I look at the web form of the router login page and it
looks like it is wrapped in JavaScript, something like an
engine-somenumbersandletters.js, so neither patator nor hydra will work on
it, it does not matter what arguments I send to the program I always either
get false positives false negatives or some error in connection, and If i
use http_fuzz and watch with wireshark, nothing is getting through to the
router (I'm running it in a VB in my PC, but the RouterOS is the same
installed in my actual router).
