### ISSUE TITLE
Ability to hide exceptions

### ISSUE THREAD

**Issue by maaaaz** [lanjelot/patator#46]
Hello @lanjelot,

Could it be possible to have a specific option (or better, make it default) to hide requests raising exceptions (for whatever reason, due a lib bug or just an expected condition) such as the following 
**`"<class 'pycurl.error'> (6, 'Could not resolve host: http')"`**:

```
$ patator http_fuzz url=http://10.0.0.1:8080
20:46:51 patator    INFO - Starting Patator v0.5 (http://code.google.com/p/patator/) at 2016-06-20 20:46 BST
20:46:51 patator    INFO - 
20:46:51 patator    INFO - code size:clen     | candidate                        |   num | mesg
20:46:51 patator    INFO - ----------------------------------------------------------------------
20:47:00 patator    FAIL - xxx  58:-1         |                                  |     1 | <class 'pycurl.error'> (6, 'Could not resolve host: http')
20:47:00 patator    INFO - Hits/Done/Skip/Fail/Size: 0/1/0/1/1, Avg: 0 r/s, Time: 0h 0m 9s
```

For large engagements this constitutes a huge spam in the result window.

Thanks !

**Comment by lanjelot** [comment]
use --allow-ignore-failures and -x ignore:

**Comment by J-alexandr** [comment]
Is this option present in current master version? Patator says he don't know such option

**Comment by lanjelot** [comment]
https://github.com/lanjelot/patator/blob/master/patator.py#L1332
