### ISSUE TITLE
can you replace the exception

### ISSUE THREAD

**Issue by d4master** [lanjelot/patator#47]
can you replace the exception
"<class 'paramiko.ssh_exception.SSHException'> Unable to connect to 127.0.0.1: [Errno 10061] No connection could be made because the target machine actively refused it"
with pretty massage 

and thank you for this terrific tool :+1:

**Comment by lanjelot** [comment]
Thanks mate. Sorry but no Patator should not try to translate error messages coming from modules as Patator (i.e. the Controller) is by design protocol-agnostic.
