### ISSUE TITLE
ERROR: xfreerdp 1.2.0-beta1 (https://github.com/FreeRDP/FreeRDP.git) is required to run rdp_login.

### ISSUE THREAD

**Issue by Stepman123** [lanjelot/patator#49]
Microsoft Windows [Version 6.1.7600]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Mozilla>cd "C:\Users\Mozilla\Downloads\patator"

C:\Users\Mozilla\Downloads\patator>patator -h
Patator v0.7-beta (https://github.com/lanjelot/patator)
Usage: patator.py module --help

Available modules:
- ftp_login     : Brute-force FTP
- ssh_login     : Brute-force SSH
- telnet_login  : Brute-force Telnet
- smtp_login    : Brute-force SMTP
- smtp_vrfy     : Enumerate valid users using SMTP VRFY
- smtp_rcpt     : Enumerate valid users using SMTP RCPT TO
- finger_lookup : Enumerate valid users using Finger
- http_fuzz     : Brute-force HTTP
- pop_login     : Brute-force POP3
- pop_passd     : Brute-force poppassd (http://netwinsite.com/poppassd/)
- imap_login    : Brute-force IMAP4
- ldap_login    : Brute-force LDAP
- smb_login     : Brute-force SMB
- smb_lookupsid : Brute-force SMB SID-lookup
- rlogin_login  : Brute-force rlogin
- vmauthd_login : Brute-force VMware Authentication Daemon
- mssql_login   : Brute-force MSSQL
- oracle_login  : Brute-force Oracle
- mysql_login   : Brute-force MySQL
- mysql_query   : Brute-force MySQL queries
- rdp_login     : Brute-force RDP (NLA)
- pgsql_login   : Brute-force PostgreSQL
- vnc_login     : Brute-force VNC
- dns_forward   : Forward DNS lookup
- dns_reverse   : Reverse DNS lookup
- snmp_login    : Brute-force SNMP v1/2/3
- ike_enum      : Enumerate IKE transforms
- unzip_pass    : Brute-force the password of encrypted ZIP files
- keystore_pass : Brute-force the password of Java keystore files
- umbraco_crack : Crack Umbraco HMAC-SHA1 password hashes
- tcp_fuzz      : Fuzz TCP services
- dummy_test    : Testing module

C:\Users\Mozilla\Downloads\patator>patator rdp_login --help
ERROR: xfreerdp 1.2.0-beta1 (https://github.com/FreeRDP/FreeRDP.git) is required to run rdp_login.
Please read the README inside for more information.
## C:\Users\Mozilla\Downloads\patator>

I do not understand what's the problem?

**Comment by ll3N1GmAll** [comment]
I am getting this issue as well. I have installed all requirements and there is nothing in the README about any other requirements. What all is required to make this tool function?
