### ISSUE TITLE
Problem in encoding "fgep" Cyrillic symbols

### ISSUE THREAD

**Issue by tmlp** [lanjelot/patator#54]
fgep does not work with the Cyrillic symbols.
how to solve a problem?
`patator.py http_fuzz url=... method=... body=....... follow=1 accept_cookie=1 -x ignore:fgrep="Кириллические символы(Cyrillic symbols)"
`
I am worked on Windows server 2012 R2

**Comment by lanjelot** [comment]
Works here on Linux. I believe your problem is that the encoding of your fgrep argument on the command line doesn't match the encoding of the string in the response.
```
$ dummy_test data=à -x ignore:fgrep=à
16:31:41 patator    INFO - Starting Patator v0.7-beta (https://github.com/lanjelot/patator) at 2017-08-21 16:31 AEST
16:31:41 patator    INFO -                                                                              
16:31:41 patator    INFO - code  size    time | candidate                          |   num | mesg
16:31:41 patator    INFO - -----------------------------------------------------------------------------
16:31:42 patator    INFO - Hits/Done/Skip/Fail/Size: 0/1/0/0/1, Avg: 1 r/s, Time: 0h 0m 0s
```

**Comment by Shinobi-sama** [comment]
if the Cyrillic encoding problem?
then how to let the program understand the desired encoding?
