### ISSUE TITLE
timeout error & debug func at http_fuzz

### ISSUE THREAD

**Issue by phatal** [lanjelot/patator#55]
Regular getting this error. 
`Traceback (most recent call last):
File "patator.py", line 3485, in debug_func
    def debug_func(t, s):
  File "patator.py", line 1195, in raise_timeout
    raise TimeoutError('timed out')
__main__.TimeoutError: timed out`
Last times with next setting
`python patator.py http_fuzz method=POST url="https://somesite.com/wp-login.php" body="log=admin&pwd=FILE0&wp-submit=Login" --threads=15 -x ignore:code=200 -x ignore,reset,retry:code=503 -x ignore,reset,retry:code=502 accept_cookie=1 -x quit:code=200,fgrep!='Forget Password' follow=1 header='Cookie: wlsid=ce5a9a166b1f312d9b4751d5bffa9cf9' --rate-limit=0 --timeout=15 --max-retries=-1 -l /root/Desktop/patator/Results/ 0=/usr/share/wordlists/seclists/Passwords/10_million_password_list_top_100000.txt`

this error doesn't crash script brute process,  but appear every 5-10 minutes.

**Comment by lanjelot** [comment]
Some responses are taking more than 15 seconds to complete and so this is why you are getting these Timeout errors. Increase the --timeout option to get rid of them.
