### ISSUE TITLE
Range and Encoding or Grab other variable

### ISSUE THREAD

**Issue by RPHAELLA** [lanjelot/patator#56]
I have 3 variable in a form to bruteforce:
- Username
- Password (Range0)
- Encrypted Password (md5(Password) or md5(Range0))

Would like to understand if there is anyway to configure patator to get other variable such that I can allow encoding to Range0 object or grab other from variable.

Thanks.

**Comment by lanjelot** [comment]
Yes there is.

```
http_fuzz url='http://blah/?username=FILE1&password=RANGE0&md5password=_@@_RANGE0__@@__ -e __@@__:md5 1=logins.txt 0=lower:a-zzz
```
