### ISSUE TITLE
Bug in handling select() function under Windows

### ISSUE THREAD

**Issue by SingularBunny** [lanjelot/patator#6]
OS Windows 7, Python 2.7.9 (default, Dec 10 2014, 12:24:55) [MSC v.1500 32 bit (Intel)],
```
C:\Python27\python.exe C:/Users/StupidUser/PycharmProjects/Nagibator/patator.py dummy_test data=RANGE0 0=hex:0x00-0xffff
02:50:21 patator    INFO - Starting Patator v0.6 (http://code.google.com/p/patator/) at 2015-03-03 02:50 ���������� ����� (����)
Traceback (most recent call last):
  File "C:\Python27\lib\logging\__init__.py", line 859, in emit
    msg = self.format(record)
  File "C:\Python27\lib\logging\__init__.py", line 732, in format
    return fmt.format(record)
  File "C:/Users/DD/PycharmProjects/Nagibator/patator.py", line 641, in format
    return logging.Formatter.format(self, record)
  File "C:\Python27\lib\logging\__init__.py", line 471, in format
    record.message = record.getMessage()
  File "C:\Python27\lib\logging\__init__.py", line 335, in getMessage
    msg = msg % self.args
TypeError: not all arguments converted during string formatting
Logged from file patator.py, line 1674
02:50:21 patator    INFO -                                                                              
02:50:21 patator    FAIL - (10038, '\xd1\xe4\xe5\xeb\xe0\xed\xe0 \xef\xee\xef\xfb\xf2\xea\xe0 \xe2\xfb\xef\xee\xeb\xed\xe8\xf2\xfc \xee\xef\xe5\xf0\xe0\xf6\xe8\xfe \xed\xe0 \xee\xe1\xfa\xe5\xea\xf2\xe5,')
Traceback (most recent call last):
  File "C:/Users/DD/PycharmProjects/Nagibator/patator.py", line 1321, in fire
    self.monitor_progress()
  File "C:/Users/DD/PycharmProjects/Nagibator/patator.py", line 1618, in monitor_progress
    self.monitor_interaction()
  File "C:/Users/DD/PycharmProjects/Nagibator/patator.py", line 1675, in monitor_interaction
    i, _, _ = select([stdin], [], [], .1)
error: (10038, '\xd1\xe4\xe5\xeb\xe0\xed\xe0 \xef\xee\xef\xfb\xf2\xea\xe0 \xe2\xfb\xef\xee\xeb\xed\xe8\xf2\xfc \xee\xef\xe5\xf0\xe0\xf6\xe8\xfe \xed\xe0 \xee\xe1\xfa\xe5\xea\xf2\xe5,')
02:50:21 patator    INFO - code  size   time | candidate                          |   num | mesg
02:50:21 patator    INFO - -----------------------------------------------------------------------------
02:50:21 patator    INFO - Hits/Done/Skip/Fail/Size: 0/0/0/0/65536, Avg: 0 r/s, Time: 0h 0m 0s
02:50:21 patator    INFO - To resume execution, pass --resume 0,0,0,0,0,0,0,0,0,0

Process finished with exit code 0
```
In current version of patator bug is in 1736 line.
`i, _, _ = select([stdin], [], [], .1)`

From python docs:
>Note: File objects on Windows are not acceptable, but sockets are. On Windows, the underlying select() function is provided by the WinSock library, and does not handle file descriptors that don’t originate from WinSock.

**Comment by SingularBunny** [comment]
My suggestion is change method 'monitor_interaction(self)':
'''Python
def monitor_interaction(self):
    from platform import system
    from sys import stdin

    command = ''

    if 'win' in system().lower():
        def add_input(input_queue):
            while True:
                input_queue.put(stdin.readline().strip())

        input_queue = Queue()

        input_thread = Thread(target=add_input, args=(input_queue,))
        input_thread.daemon = True
        input_thread.start()
        input_thread.join(.1)
        if input_queue.empty(): return
        command += input_queue.get()
    else:
        i = select([stdin], [], [], .1)[0]
        if not i: return
        command += i[0].readline().strip()

    if command == 'h':
      logger.info('''Available commands:
       h       show help
       <Enter> show progress
       d/D     increase/decrease debug level
       p       pause progress
       f       show verbose progress
       x arg   add monitor condition
       a       show all active conditions
       q       terminate execution now
       ''')
#5 .........and other
'''

**Comment by SingularBunny** [comment]
The most awesome way to use `msvcrt` module to modify `monitor_interaction` method:
```python
 def monitor_interaction(self):
    from platform import system

    command = ''

    if 'win' in system().lower():
        import msvcrt
        if msvcrt.kbhit():
            command += msvcrt.getwch()
    else:
        from sys import stdin
        i, _, _ = select([stdin], [], [], .1)
        if not i: return
        command += i[0].readline().strip()

    if command == 'h':
      logger.info('''Available commands:
       h       show help
       <Enter> show progress
       d/D     increase/decrease debug level
       p       pause progress
       f       show verbose progress
       x arg   add monitor condition
       a       show all active conditions
       q       terminate execution now
       ''')
#........other code
```
Im tested this in win 7. Work fine.

**Comment by lanjelot** [comment]
hey mate, thanks for reporting and provide some workaround. I've been working on adding Windows support to patator. Stay tuned.

**Comment by lanjelot** [comment]
should work now with b08d5357dc3d8f8cf64da2e176618bfd4ed02633
