### ISSUE TITLE
Quiet Option

### ISSUE THREAD

**Issue by IAmAStealer** [lanjelot/patator#60]
I'm trying to use Patator in a integration system.
The problem is that it doesn't wait enter key to print the Progress into the console output, it makes many many many useless verbose.
I couldn't find quiet option I tried to change some code by my side but it leads into anempty report or an endless script. (because I don't get all the program of course).
Is it possible to produce a quiet global options so you just get the reports at the end ?

maybe it's already available but I couldn't see it.
Thanks.

EDIT : 
Found how to do it. It's a bit dirty but that's what I changed :
Patator.py :
line 1328 add > `opt_grp.add_option('-q', '--quiet', dest='quiet', type='int', default=0, metavar='N', help='No progress report')`
line 1373 add > `self.quiet = opts.quiet`
line 1998 add > `if self.quiet == 0:`
then include the logger.info inside the if.

start patator and add option : -q 1 for example.

**Comment by lanjelot** [comment]
Hi, I'm not sure I understand your issue. Why don't you use `2>/dev/null` to make patator quiet and pass the -l option to be able to parse the reports. Cheers
