### ISSUE TITLE
Feature: Load raw request from file (Module http_fuzz)

### ISSUE THREAD

**Issue by vdun** [lanjelot/patator#61]
Load a raw request from a file and fuzz the parameters in it. This would make it easier to use in more complex scenarios.

**Comment by lanjelot** [comment]
Good idea. It should be as simple as parsing the raw_request module parameter to populate the other parameters, like this:
```
def execute(...):
...
  if raw_request:
    method, path, query, host, headers, body = parse(raw_request)
```
However, I can't think of a way to find out whether the request is HTTPS or HTTP that way. The user will still need to specify the `scheme` parameter. 

Or maybe i'm missing something?

**Comment by lanjelot** [comment]
@vdun thoughts on 02783fb?
