### ISSUE TITLE
Any plans to support ipv6? (I think it doesn't currently)

### ISSUE THREAD

**Issue by insidetrust** [lanjelot/patator#62]
There are not many password attack tools supporting ipv6 currently - which leaves very limited options on a pentest in a v6 network.

I got Hydra working with ssh and ipv6 a while back, but even that doesn't seem to work any more (in 8.5 I can't get this working any more).

I.e. I want to be able to guess credentials for something like ssh benw@fe80::7b95:bca6:7457:d9ce%eth0

Any thoughts on how much work this would be?

**Comment by lanjelot** [comment]
It depends on the module and more specifically, the lib that the module relies upon. For the ssh module for example, `paramiko` seems to support ipv6. I must admit i've never tested ipv6 with patator, but for ssh have you tried [this](https://stackoverflow.com/questions/31956313/python-paramiko-and-ipv6-ssh)?

**Comment by ArgentEnergy** [comment]
@insidetrust I also ran into this issue with both tools. Metasploit's auxiliary/scanner/ssh/ssh_login module supports IPv6 for anyone else that doesn't know.
