### ISSUE TITLE
AttributeError RPI

### ISSUE THREAD

**Issue by simepy** [lanjelot/patator#66]
Hello,

In Raspberry Pi (Linux raspberrypi 4.9.36-v7+ #1015 SMP Thu Jul 6 16:14:20 BST 2017 armv7l GNU/Linux):

I have this error I just do python2 ./patator : 
`Traceback (most recent call last):
  File "./patator.py", line 3461, in <module>
    class HTTP_fuzz(TCP_Cache):
  File "./patator.py", line 3511, in HTTP_fuzz
    'socks4a': pycurl.PROXYTYPE_SOCKS4A,
AttributeError: 'module' object has no attribute 'PROXYTYPE_SOCKS4A'`

Any idea ?

Thanks

**Comment by lanjelot** [comment]
hey, you probably need to install a newer version of pycurl/curl. See version requirements within patator.py
