### ISSUE TITLE
Not working on windows 10?

### ISSUE THREAD

**Issue by IsmithaDEV** [lanjelot/patator#68]
Hi, today i just decided to test patator, but when i had everything ready to work with it i saw that this was happening.

I open CMD, cd to the patator directory and run it, after this i execute this console comand:
`patator.exe http_fuzz url="http://localhost/phpmyadmin/index.php" method=POST body='pma_username=root&pma_password=FILE00&server=1&target=index.php' 0=passwords.txt follow=1 accept_cookie=1 -x ignore:fgrep='Cannot log in to the MySQL server'`

This is what the console return to me: 

`16:09:23 patator    INFO - Starting Patator v0.7-beta (https://github.com/lanjelot/patator) at 2017-08-11 16:09 Hora de verano romance
16:09:23 patator    INFO -
16:09:23 patator    INFO - code size:clen       time | candidate                          |   num | mesg
16:09:23 patator    INFO - -----------------------------------------------------------------------------
16:09:24 patator    INFO - 200  96627:-1       0.391 |                                    |     1 | HTTP/1.1 200 OK
16:09:24 patator    INFO - Hits/Done/Skip/Fail/Size: 1/1/0/0/1, Avg: 0 r/s, Time: 0h 0m 1s
"pma_password" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"server" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.
"target" no se reconoce como un comando interno o externo,
programa o archivo por lotes ejecutable.`

If we translate the spanish part, it say that pma_password, server and target are not recognized as a internal or external command.

What is happening? How can i make it work well?

I downloaded the patator already compiled from https://github.com/maaaaz/patator-windows

I am using windows 10 pro.
Thanks!

**Comment by ruimgoncalves** [comment]
The problem is with the command line interpreter, windows ignores & inside " but not inside ', so you have to change a litle bit the command.

I haven't tested but this should work

``` console
patator.exe http_fuzz url="http://localhost/phpmyadmin/index.php" method=POST body="pma_username=root&pma_password=FILE00&server=1&target=index.php" 0=passwords.txt follow=1 accept_cookie=1 -x ignore:fgrep="Cannot log in to the MySQL server"
```
