### ISSUE TITLE
Add ability to stop brute forcing if x numbers of errors occur in a row

### ISSUE THREAD

**Issue by DanMcInerney** [lanjelot/patator#7]
I'm testing the telnet bruting and the attempts/sec slow to a crawl after like 8 tries and it starts throwing FAIL messages the rest of the time. Is there an option to have it stop attempting to brute after so many FAILs?

**Comment by lanjelot** [comment]
You have two options:
 - use the -x free action to stop testing that host. For example pass -x free=host:fgrep="timed out" and patator will stop testing the host that caused a "timed out" FAIL message (more examples in patator.py). By default, patator retries the same payload 4 times before reporting it as a FAIL, so you can pass --max-retries 8 to increase the number of retries.

- alternatively, you could just pause during execution (press p) after you've seen too many FAIL messages, then add a new free action with:
x free=host:fgrep=timed out
And resume execution (press p again).
