### ISSUE TITLE
PROXYTYPE_SOCKS4A

### ISSUE THREAD

**Issue by Cenzor** [lanjelot/patator#71]
Hi, i have a trouble.
For example:
`python patator.py rdp_login host=FILE0 user=FILE1 password=FILE2 0=ip.txt 1=logins.txt 2=passwds.txt`
output:
`Traceback (most recent call last):`
`  File "patator.py", line 3464, in <module>`
`    class HTTP_fuzz(TCP_Cache):`
`  File "patator.py", line 3514, in HTTP_fuzz`
`    'socks4a': pycurl.PROXYTYPE_SOCKS4A,`
`AttributeError: 'module' object has no attribute 'PROXYTYPE_SOCKS4A'`

Please help. 
P. S.: uname -a:
Linux debian 3.16.0-4-amd64 #1 SMP Debian 3.16.7-ckt25-2+deb8u3 (2016-07-02) x86_64 GNU/Linux

**Comment by lanjelot** [comment]
Try with pycurl-7.19.3 and libcurl-7.21.0

**Comment by Cenzor** [comment]
I installed this packets:
root@debian:/home/patator# dpkg --list | grep libcurl3
ii  libcurl3:amd64                       7.38.0-4+deb8u5                   amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  libcurl3-gnutls:amd64                7.38.0-4+deb8u4                   amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
root@debian:/home/patator# dpkg --list | grep pycurl
ii  python-pycurl                        7.19.5-3                          amd64        Python bindings to libcurl
ii  python3-pycurl                       7.19.5-3                          amd64        Python bindings to libcurl (Python 3)

**Comment by lanjelot** [comment]
hum ok then maybe try with a more recent version of libcurl and pycurl

**Comment by Cenzor** [comment]
How i can do it? When i install packets, then package pycurl install with version 7.19.5-3 default and package libcurl install with version 7.38.0-4 default. How do i install 7.19.3 and 7.21.0?

**Comment by Cenzor** [comment]
In patator.py i delete strings:
3514 - 'socks4a': pycurl.PROXYTYPE_SOCKS4A,
3516 - 'socks5_with_hostname': pycurl.PROXYTYPE_SOCKS5_HOSTNAME,
And in string 3496 delete parametr 'socks4a'
It is worked
