### ISSUE TITLE
Iterate over two parameters at the same time.

### ISSUE THREAD

**Issue by Pwdrkeg** [lanjelot/patator#86]
Is it possible to iterate over two parameters at the same time?  For example, if you wanted to iterate a NET0 and a FILE0:

10.10.10.1 and password1
10.10.10.2 and password2
10.10.10.3 and password3

**Comment by lanjelot** [comment]
No but you could create a combo file first and then use the COMBO keyword in your command line like so: `host=COMBO00 password=COMBO01`
