### ISSUE TITLE
Proxy not seeing traffic afer adding before_header/before_egrep

### ISSUE THREAD

**Issue by derrabe** [lanjelot/patator#87]
Hi,

I am trying to debug some patator http_fuzz requests which need CSRF tokens. I am using before_urls, before_header and before_egrep to extract the token. I notice that the http_proxy option works normally in patator, but when I add these 3 options, the proxy sees no traffic (like the proxy option is being ignored).
I tested this by removing them one by one, and with just before_urls, the proxy option works. Once before_header/before_egrep is added, the proxy sees no traffic and the requests go direct.

Is this by design?

**Comment by lanjelot** [comment]
No this should work, can you paste your command line and output when passing the --debug option?

**Comment by derrabe** [comment]
Here is the command line:
```
patator  http_fuzz  method=GET  follow=0  accept_cookie=0 --debug  --threads=1  timeout=5  --max-retries=0 http_proxy=127.0.0.1:8080 url="http://IP/test/index.php/?username=admin&password=FILE0&user_token=_CSRF_&Login=Login" 0=./passwords.txt header="Cookie: security=high; PHPSESSID=$SESSIONID" before_urls="http://IP/test/" before_header="Cookie: security=high; PHPSESSID=$SESSIONID" before_egrep="_CSRF_:<input type='hidden' name='user_token' value='(\w+)' />" -x quit:fgrep='Success'
```
This does not go through the proxy, and gives errors like:
```
patator   DEBUG [Thread-1] payload: {'url': 'http://IP/test/index.php/?username=admin&password=admin&user_token=_CSRF_&Login=Login', 'before_egrep': "_CSRF_:<input type='hidden' name='user_token' value='(\\w+)' />", 'http_proxy': '127.0.0.1:8080', 'method': 'GET', 'header': 'Cookie: security=high; PHPSESSID=redacted', 'timeout': '5', 'accept_cookie': '0', 'follow': '0', 'before_urls': 'http://IP/test/', 'before_header': 'Cookie: security=high; PHPSESSID=redacted'} [try 1/1]
03:26:00 patator   DEBUG [Thread-1] except: <type 'exceptions.TypeError'> ("execute() got an unexpected keyword argument 'before_header'",)
```

However this does not give errors, and goes through the proxy:
```
patator  http_fuzz  method=GET  follow=0  accept_cookie=0 --debug  --threads=1  timeout=5  --max-retries=0 http_proxy=127.0.0.1:8080 url="http://IP/test/index.php/?username=admin&password=FILE0&user_token=_CSRF_&Login=Login" 0=./passwords.txt header="Cookie: security=high; PHPSESSID=$SESSIONID" before_urls="http://IP/test/"
```

Am I putting something in the wrong order? Any other obvious issues with the way I am doing it?

**Comment by lanjelot** [comment]
Can you make you are using the latest version? The error message basically says your version of patator does not know about the `before_header` option...

**Comment by derrabe** [comment]
I had 2 versions installed, 0.6 and 0.7. 0.6 was being called in the above commands and specifying 0.7 fixed that. Thanks!
