### ISSUE TITLE
ERROR: xfreerdp 1.2.0-beta1 (https://github.com/FreeRDP/FreeRDP.git) is required to run rdp_login. 

### ISSUE THREAD

**Issue by ll3N1GmAll** [lanjelot/patator#91]
./patator.py rdp_login --help
ERROR: xfreerdp 1.2.0-beta1 (https://github.com/FreeRDP/FreeRDP.git) is required to run rdp_login. 
I see this documented here with no response: https://github.com/lanjelot/patator/issues/49
I am getting this issue as well. I have installed all requirements and there is nothing in the README about any other requirements. What all is required to make this tool function?

**Comment by RoberMB** [comment]
Hi, you can follow the instructions to install freerdp:

https://github.com/FreeRDP/FreeRDP/wiki/Compilation

After that rdp_login patator module works:

# python patator.py rdp_login -h
Patator v0.7 (https://github.com/lanjelot/patator)
Usage: rdp_login <module-options ...> [global-options ...]

Examples:
  rdp_login host=10.0.0.1 user='administrator' password=FILE0 0=passwords.txt

Module options:
  host          : target host
  port          : target port [3389]
  user          : usernames to test
  password      : passwords to test 
...
...

Regards!
