### ISSUE TITLE
suggestion - didn't know where else to write it

### ISSUE THREAD

**Issue by wertdnijekfof** [lanjelot/patator#94]
Hello, 
great tool maybe a complete hydra replacement .. I can hope. 
I'm an old hydra user but during one of my pentests I was trying to gain access to the Thomson SOHO router and to my surprise I realized that the login form provided by the router is ".lua", not ".php" or ".htm" or " .aspx". I was wondering if such option exist in PATATOR to bruteforce a .lua form digest (username and password) on this router and if it not, will it be included in the future release of PATATOR ?
So far, Hydra still doesn't understand this type of form.

**Comment by lanjelot** [comment]
digest auth is supported, use auth_type=digest
