### ISSUE TITLE
how can i run patator in background?

### ISSUE THREAD

**Issue by TheRogue27** [lanjelot/patator#99]
i did a script file with the command and run nohup ./script & to see the output and i get an error

07:17:01 patator    INFO - Starting Patator v0.7 (https://github.com/lanjelot/patator) at 2018-10-12 07:17 CEST
ERROR:root:[Errno 9] Bad file descriptor
Traceback (most recent call last):
  File "/usr/local/bin/patator.py", line 1598, in fire
    self.monitor_progress()
  File "/usr/local/bin/patator.py", line 1940, in monitor_progress
    self.monitor_interaction()
  File "/usr/local/bin/patator.py", line 2010, in monitor_interaction
    command = i[0].readline().strip()
IOError: [Errno 9] Bad file descriptor

does anyone have any ideea how i can run in background?

**Comment by freeload101** [comment]
screen -L -S patator_scan 
tmux ?
theres also the tee command bro 

date | tee out.txt
